server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server.git.uri: https://github.com/GaryChengld/microservices-examples-config-repo.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/