spring:
  application:
    name: zuul-gateway

server:
  port: 9080

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
#  ignoredServices: '*'
  routes:
    pet:
      path: /v1/pet/**
      serviceId: PET
      stripPrefix: false
    review:
      path: /v1/review/**
      serviceId: REVIEW
      stripPrefix: false
