server:
  port: 9080

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000